DROP TABLE IF EXISTS t;

CREATE TABLE t
(
    `n` Int8,
    `s` String,
    CACHE n FIFO c1(INTERVAL 1 Hour, INTERVAL 2 Day)
)
ENGINE = MergeTree
ORDER BY n
CACHE CS c1(INTERVAL 2 Minute, INTERVAL 3 Month), FIFO c2(INTERVAL 2 Day, INTERVAL 4 Day);

ALTER TABLE t DROP CACHE c2;

SHOW CREATE TABLE t;
SELECT ' ';

ALTER TABLE t
    ADD CACHE FIFO c3(INTERVAL 2 Hour, INTERVAL 4 Day);

SHOW CREATE TABLE t;
SELECT ' ';

ALTER TABLE t
    MODIFY COLUMN CACHE n CS c1(INTERVAL 2 Day, INTERVAL 4 Day);
ALTER TABLE t
    MODIFY COLUMN CACHE n CS c2(INTERVAL 2 Day, INTERVAL 4 Day);


SHOW CREATE TABLE t;
SELECT ' ';

ALTER TABLE t MODIFY COLUMN CACHE DROP n c2;

SHOW CREATE TABLE t;
SELECT ' ';

DROP TABLE t;
